//------------------------------------------------------------------------------
// <auto-generated>
//     This codes have been generated by assistance of tools
//     Current version:4.0.30319.42000
//
//     Any changes to this file may exhibit incorrect behavior and if
//     the codes are regenerated, these changes will be lost
//     
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysBot.Pokemon.WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
